### ISSUE TITLE
my data has 9932 WOS entries, but tethne only reads 9902 entries. 

### ISSUE THREAD

**Issue by yzou20** [diging/tethne#106]
If you want the data, please email me. --Yawen

**Comment by erickpeirson** [comment]
Hmm, that's odd; is it possible that there are duplicates?

Please do send the data along

## 

https://asu.academia.edu/ErickPeirson
Postdoctoral Researcher
Arizona State University

**Comment by erickpeirson** [comment]
I'm going to go ahead and close this. We can re-open if anyone can reproduce the problem and provide sample data.

**Comment by ma-ji** [comment]
This is possible: the field (e.g. UT/DOI) used to build index should not have duplicates. Otherwise, records in corpus will be less than in the raw dataset. I had a similar issue, what I did is deleting all the fields of UT/DOI, and then use the auto-generated id instead. I'm not sure if this way makes sense? @erickpeirson
