### ISSUE TITLE
ImportError tethne.readers as rd

### ISSUE THREAD

**Issue by tomvannuenen** [diging/tethne#136]
Dear Eric,

I'm trying to run Tethne but am running into trouble when trying to import the module. Running `$ pip show tethne` yields:

```
Metadata-Version: 1.0
Name: tethne
Version: 0.7.25
Summary: Bibliographic network and corpus analysis for historians
Home-page: http://diging.github.io/tethne/
Author: Erick Peirson
Author-email: erick [dot] peirson [at] asu [dot] edu
License: GNU GPL 3
Location: /Users/tomvannuenen/anaconda/envs/py34/lib/python3.4/site-packages
Requires: networkx, Unidecode, iso8601, rdflib, chardet, html5lib, isodate, pdfdocument, pdfminer3k, python-magic, slate, Unidecode, nltk
```

But when trying to importing Tethne in Python 3.x with `import tethne.readers as rd`, Python tells me:
`ImportError: No module named 'tethne.readers'; 'tethne' is not a package`

When trying the same in Python 2.7:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "tethne.py", line 3, in <module>
    import tethne.readers as rd
ImportError: No module named readers
```

I tried uninstalling/reinstalling a number of times, to no avail. Do you have any clue as to what am I doing wrong?

**Comment by erickpeirson** [comment]
Hi @tomvannuenen, thanks for trying `tethne`. Tethne is not yet compatible with Python 3.x, so I'm not surprised on that front. For Python 2.7, I wonder if there is something funky going on with multiple versions of Python -- what happens when you install Tethne the "old-fashioned" way? i.e. download the [latest release](https://github.com/diging/tethne/releases), and then `python setup.py install` ?

**Comment by erickpeirson** [comment]
I'm going to go ahead and close this for now, on the theory that this is a Python installation issue rather than a bug in Tethne. If anyone has more details, we can reopen it.
