### ISSUE TITLE
value error importing metadata zotero RDF

### ISSUE THREAD

**Issue by TSchroth** [diging/tethne#144]
Hi Erick and Team,
trying to parse a zotero RDF metadata of ca. 800 articles including abstracts, with 
`zotero_export_path = '/Users/schroth/Desktop/SOEP/SOEP'

metadata = zotero.read(zotero_export_path, index_by='link', follow_links=False)`
seeing this 

<img width="872" alt="zoterovalueerror" src="https://cloud.githubusercontent.com/assets/18705678/15351327/164d3b5a-1cdf-11e6-912d-f0356f92d0ce.png">

using anaconda 1.4.0, python 2.7.11
on a jupyter notebook with 

`import nltk`
`from tethne.readers import zotero`
`import matplotlib.pyplot as plt`
`from nltk.corpus import stopwords`
`import gensim`
`import networkx as nx`
`import pandas as pd`

`from collections import defaultdict, Counter`

`wordnet = nltk.WordNetLemmatizer()`
`stemmer = nltk.SnowballStemmer('english')`
`stoplist = stopwords.words('english')`

Thank you

**Comment by erickpeirson** [comment]
@TSchroth @janako Can you try the latest version of tethne (just released), v0.7.30 (cef285e85a08cd2ce2e83a215d1cda0906f2d3a1), and confirm that the bug is (or isn't) fixed?

Be sure to install the latest version from PyPI:

``` shell
$ pip install -U tethne
```

and restart your kernel if you are currently working in a Jupyter notebook.
