### ISSUE TITLE
Using Mallet file as corpus for the LDA model

### ISSUE THREAD

**Issue by pucek80** [diging/tethne#149]
@erickpeirson ,

I am wondering if it is possible to use the file created via Mallet's import-dir function as corpus object for LDAModel? I've been going through the topic models visualization tutorial and that is where I am stuck. I have textual data in multiple files. With the more recent improvement to Tethne, it appears that the older tutorials don't work anymore. I will greatly appreciate any help!

**Comment by erickpeirson** [comment]
@pucek80 Apologies for the delayed response. Two quick replies:

Reply 1. The docs are horribly out of date, and I am just this moment sprinting to update them. Give me a few days, and I'll update this thread when the updated docs are available (including the LDA tutorial).

Reply 2. Hmmm... that's a bit of a different use-case than we have previously had in mind. In most use-cases that we envisioned, the user would start with heterogenous data and metadata, use Tethne to bring those together into a corpus with structured feature data (e.g. wordcounts), and then let Tethne interface with MALLET -- in other words, intervene before your `import-dir` step. 

So, I guess there are two routes we can take here. These are not mutually exclusive, but it would be helpful to hear your reaction.
1. We can make it easier for you to encapsulate your textual data in a Corpus, so that Tethne can handle things as I've described above, or 
2. We can add a method to LDAModel that allows you to start mid-stream, i.e. provide the path of the MALLET-serialized Corpus, and go from there.

Thoughts?

**Comment by erickpeirson** [comment]
Well, that was more than a few days, but here's the updated LDA tutorial: http://diging.github.io/tethne/tutorial.mallet.html

@pucek80 Any thoughts on which strategy would be most helpful?

**Comment by erickpeirson** [comment]
For cross-reference, this is related to #122

**Comment by erickpeirson** [comment]
@pucek80 Take a look at [this thread](https://groups.google.com/forum/#!topic/tethne-users/3BAPhBXPGkk). Does that help at all?

**Comment by erickpeirson** [comment]
Closing for now. Please re-open if this is not resolved.

**Comment by pucek80** [comment]
Erick, thank you for all the updates. I was sidetracked with other projects and never really got a chance to get back to this one. I will definitely take a look and let you know.
