### ISSUE TITLE
 error with import Scopus data in tethne package on python

### ISSUE THREAD

**Issue by faryou** [diging/tethne#62]
![tethne2](https://cloud.githubusercontent.com/assets/10322370/6059231/4d372a06-ad44-11e4-94b3-76484dc95035.JPG)

**Comment by erickpeirson** [comment]
Hi @faryou , thanks for posting this. Can you send along the file that you're trying to parse, so that I can take a look? The Scopus reader is not very polished, so I wouldn't be surprised to find a few kinks.

**Comment by faryou** [comment]
Hi
tanx a lot...
I amator in tethne so maybe error belong me but this error is very simple...
the file is

**Comment by erickpeirson** [comment]
Hi @faryou ; looks like the attachments didn't come through. Can you send them directly, to erick [dot] peirson [at] asu [dot] edu ?

**Comment by faryou** [comment]
I send you  the data 6 days ago but not answer...

**Comment by faryou** [comment]
hi  i don't received answer for my error!!!
please help me.

**Comment by erickpeirson** [comment]
Hi @faryou; just so you know, this is maintained as a side project as I have the time -- nobody gets paid for this. So, sorry, I'll help as I am able.

Did you take a look at the documentation linked from #61? Sounds to me like the Scopus data are not formatted as expected. Try downloading them again, following the instructions linked from issue #61. In the meantime, I'll keep this issue open so that I'm sure to write some more tests for the next release.

Again, the Scopus reader is experimental, so this is not unexpected. We'll get to it when we can.
